[package]
name = "rust-workshop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
duct = "0.13.6"
glob = "0.3.1"
gumdrop = "0.8.1"
indoc = "2.0.4"
